### ISSUE TITLE
doc ja: grant ALL on SCHEMA pgroonga to user

### ISSUE THREAD

**Issue by hiroyuki-sato** [pgroonga/pgroonga.github.io#12]
``grant ALL on SCHEMA pgroonga to user;``の説明がどこかにあると良いように思います。

で良い場所が思いつかなないので、``create extension pgroonga``の説明をリファレンスに入れて
その中で説明をするのが良いのかも...と思いました。

他に良い場所があればそちらで良いと思います。

``grant ALL on SCHEMA pgroonga to user;``という項目でも良い気がしてきました。

## create extension pgroonga

``create extension pgroonga``は、PGroongaを利用するために最初に実行するコマンドです。
コマンドは、PGroongaを利用するデータベース内で実行してください。このコマンドの実行には管理者権限が必要です。

```
psql# CREATE EXTENSION pgroonga
```
 

PGroongaが利用できる状態かどうかは次のコマンドを使って確認できます。

```
psql# \x
psql# select * from pg_extension;
-[ RECORD 2 ]--+---------
extname        | pgroonga
extowner       | 10
extnamespace   | 2200
extrelocatable | f
extversion     | 1.0.1
extconfig      | 
extcondition   | 
```

extname: ``pgroonga``というエントリがある場合、現在のデータベース上でPGroongaが利用可能です。
extversionは、pgroongaのバージョンを表しています。

## スキーマ

``create extension pgroonga``を実行した場合、``pgroonga``というスキーマが自動的に作成されます。
スキーマの存在有無は次のコマンドで確認をすることができます。

```
psql# \dn
   List of schemas
   Name   |  Owner   
----------+----------
 pgroonga | postgres
 public   | postgres
(2 rows)
```

初期状態では、管理者のみがpgroongaスキーマのアクセス権限を持っています。

pgroongaのアクセス権限は、``create index .. using pgroonga(... pgroonga.text_regexp_ops)``や
``create index .. using pgroonga(... pgroonga.varchar_regexp_ops)``を実行する際に必要です。

所定のユーザにpgroongaスキーマへのアクセス権限を付与するためには次のコマンドを管理者権限で実行します。

```
# grant ALL on SCHEMA pgroonga to user;
GRANT
```

``user``は権限を付与するユーザの名前です。

**Comment by hiroyuki-sato** [comment]
https://github.com/pgroonga/pgroonga.github.io/issues/9 より

> CREATE INDEXの権限は http://pgroonga.github.io/ja/reference/create-index-using-pgroonga.html の方がいいんじゃないかと思いました。

ということでhttp://pgroonga.github.io/ja/reference/create-index-using-pgroonga.htmlに追加する。

**Comment by kou** [comment]
http://pgroonga.github.io/ja/reference/grant-usage-on-schema-pgroonga.html に`GRANT USAGE ON SCHEMA pgroonga TO user`のドキュメントを書きました。

**Comment by hiroyuki-sato** [comment]
ありがとうございます。大変わかりやすいです。
