### ISSUE TITLE
pgroonga object isn't found

### ISSUE THREAD

**Issue by yongxianggao-chanjet** [pgroonga/pgroonga.github.io#20]
On MacBook, I see follow error since pgroonga-1.1.8 when I make a mvn build of a module called "common-test"

ERROR:  pgroonga: object isn't found: <Sources366583664>
CONTEXT:  automatic analyze of table "common-test.csp_appdata.customer"

An interesting fact is that, this error shows up about 1 minute after the mvn build finishes.

**Comment by kou** [comment]
This repository is for https://pgroonga.github.io/ not for PGroonga itself.
Could you report it to https://github.com/pgroonga/pgroonga/issues ?
