### ISSUE TITLE
PGroonga の発音表記は間違っていると思いますが。

### ISSUE THREAD

**Issue by ShikiSuen** [pgroonga/pgroonga.github.io#324]
ホームページによると：
```
PGroonga (píːzí:lúnɡά) is a PostgreSQL extension to use [Groonga](http://groonga.org/) as the index.
```
<img width="1393" alt="image" src="https://github.com/pgroonga/pgroonga.github.io/assets/3164826/7f508370-a1a5-4932-9902-a81d2dd28568">

であるが、その発音表記は読むと「ぴーじーるんが」と全く違って、「ぴーづぃーるんが（PZloonga）」になります。

問題点は「G」の子音であり、「z」でなく「dʒ」であると思います。

愚見は以上です。よろしくお願いいたします。

**Comment by kou** [comment]
そうなんですね！

私は発音記号はよくわからないので、教えてもらった通り「dʒ」に変更しました！
