### ISSUE TITLE
日本語サイトのリファレンスマニュアルページでpgroonga 1.xへのリンクエラー

### ISSUE THREAD

**Issue by hiro7355** [pgroonga/pgroonga.github.io#33]
https://pgroonga.github.io/ja/reference/
こちらのページの
「これはPGroonga 2.X用のドキュメントです。古いPGroongaを使っているならPGroonga 1.xのドキュメントを見てください。」
のリンクをクリックすると、404エラーとなってしまいます。

**Comment by kou** [comment]
直しました！
