### ISSUE TITLE
Add reference for pgroonga_condition() function

### ISSUE THREAD

**Issue by komainu8** [pgroonga/pgroonga.github.io#335]
## What is your problem?

We can use `pgroonga_condition()` function since PGroonga 3.1.6.
We recommend whitch PGroonga users use `pgroonga_condition()` from now on.

However, this function have not reference.
Therefore, general PGroonga users can not know usage this function.

## My suggestions

I will update the following documents.

- [x] `reference/functions/pgroonga-condition.md`

  - [x] Update "Summary"
  - [x] Translate "Summary"
  - [x] Update "Syntax"
  - [x] Translate "Syntax"
  - [x] Update "Usage"
  - [x] Translate "Usage"

- [x] `reference/operators/query-v2.md`

  - [x] Update "Syntax"
  - [x] Translate "Syntax"
  - [x] Update "Usage"
  - [x] Translate "Usage"

- [x] `reference/operators/prefix-search-v2.html`

  - [x] Update "Syntax"
  - [x] Translate "Syntax"
  - [x] Update "Usage"
  - [x] Translate "Usage"

**Comment by kou** [comment]
We should add a comment where the related documentations exist to https://github.com/pgroonga/pgroonga/issues/100 after we write them.

**Comment by abetomo** [comment]
`reference/functions/pgroonga-condition.md`: #368
