### ISSUE TITLE
Cannot install groonga-tokenizer-mecab on CentOS8

### ISSUE THREAD

**Issue by s-araki-issp** [pgroonga/pgroonga.github.io#60]
The installation page states that groonga-tokenizer-mecab can be installed, but the package did not exist and could not be installed.
https://pgroonga.github.io/install/centos.html
https://packages.groonga.org/centos/8/x86_64/Packages/

It existed for CentOS7 and CentOS6.

Will it be released for CentOS8?

Thank you.

**Comment by kou** [comment]
We need `mecab-devel` package for CentOS 8 but EPEL for CentOS 8 doesn't provide it: https://bugs.centos.org/view.php?id=16668
We can release it for CentOS 8 once `mecab-devel` package is available.

Please contact to CentOS 8 (or EPEL?) developers.
