### ISSUE TITLE
Is fulltext search not work when input query just One character?

### ISSUE THREAD

**Issue by at-hungnguyen** [pgroonga/pgroonga.github.io#63]
Hi, please help me

Example i have data: contents table
id - content(varchar)
1  - Test me please 
Index: 
`
CREATE INDEX test_index
            ON contents
            USING pgroonga (content pgroonga_varchar_full_text_search_ops_v2) WITH (tokenizer='TokenMecab');
`
When i search by query
`SELECT content FROM contents where content &@ 'T'`;
it will return empty.
Is it function or a bug?

**Comment by komainu8** [comment]
Thank you for your report.
However, I could not reproduce this problem in my environment.

```sql
create table contents ( id integer, content varchar );

CREATE INDEX test_index ON contents USING pgroonga (content pgroonga_varchar_full_text_search_ops_v2) WITH (tokenizer='TokenMecab');

insert into contents values (1, 'Test me please');

select * from contents;
 id |    content     
----+----------------
  1 | Test me please
(1 row)

SELECT content FROM contents where content &@ 'T';
    content     
----------------
 Test me please
(1 row)
```

Could you provide SQL to reproduce this case from scratch?
And could you teach me your PostgreSQL and PGroonga version?

**Comment by at-hungnguyen** [comment]
I'm using
PGroonga 2.2.5
Groonga 10.0.2
MeCab 0.996 + IPADIC 2.7.0-20070801
PostgreSQL 9.6 / Alpine Linux


Can you explain this query to make sure it run on pgroonga index?

**Comment by at-hungnguyen** [comment]
Here is my full informations:

> CREATE TABLE test_users (
    id BIGSERIAL PRIMARY KEY,
    display_name character varying(191),
    account_name character varying(191) NOT NULL UNIQUE,
    first_name character varying(100),
    last_name character varying(100),
    email character varying(254) NOT NULL,
    password character varying(255),
    timezone character varying(255) NOT NULL,
    avatar_path character varying(255),
    avatar_name character varying(255),
    role_code integer NOT NULL REFERENCES roles(id),
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    first_name_en character varying(100),
    last_name_en character varying(100),
    registered_by character varying(256),
    language character varying(100),
    last_login_datetime timestamp(0) without time zone,
    occupation_code integer REFERENCES occupations(occupation_code),
    registration_status_code integer REFERENCES registration_status(registration_status_code),
    jwt_generate_at timestamp(0) without time zone,
    start_page_url character varying(2048)
);

**Comment by at-hungnguyen** [comment]
It's really an urgent issue for me.
Hope that you can check it for me soon.
Really thank you so much!

**Comment by at-hungnguyen** [comment]
I think it's same with this issue
https://github.com/pgroonga/pgroonga/issues/130
But i have no idea with TokenMecab tokenizer

**Comment by kou** [comment]
This repository is for the PGroonga website not PGroonga itself.
Please use https://github.com/pgroonga/pgroonga instead.
