### ISSUE TITLE
doc: リリース手順を最新にする

### ISSUE THREAD

**Issue by HashidaTKS** [pgroonga/pgroonga.github.io#86]
* GITHUB_TOKEN を指定しなくても動いた。もう不要かもしれない。要確認。
* LAUNCHPAD_UPLOADER_PGP_KEYって何？となる気がするので、Groongaのリリース手順にでもリンクを貼るのが良いのでは。
* パッケージ作成可能かどうか確認
  * タグを打つ前に、launchpadのnightlyを使って、Ubuntuのパッケージが上手くビルドできるか確認する。
  * launchpadのppaとnightlyを切り替える、.dput.cfについても記載する
  * その際、make distして手元でソースアーカイブを作って試す必要がある。
  * `make dist` -> .dput.cfの宛先がnightly担っていることを確認 -> `rake package:ubuntu`
* タグを打った後、最新のGithub Actionsの結果からソースアーカイブ pgroonga-xxxx.tar.gzをPGroongaのリポジトリのトップに持ってくる必要がある旨を記載する。
  * 上記のファイルは現在作成されていない。作成するように修正する必要がある。
  * その上で、ダウンロードは自動化してもよいが、内部的にどういう手順を踏む必要があるのかの解説のため、ダウンロードが必要という手順には書いておいても良さそう。
* リリース用アーカイブファイルの作成
  * make distする必要がないことを記載する(Ubuntuのnightlyでビルドテストするときは必要かも)
  * ソースアーカイブはタグを打ったGithub Actionsの結果からGroongaのトップディレクトリに持ってくる必要があることを記載する。
  * rakeの際に自動で持ってくるようにしたいが、いずれにしろ手順として内部的にそういうことをすることは記載しておく必要がありそう
  * ここでいうソースアーカイブはmake distの結果も含まれているもので、groonga-xxxx.tar.gzのこと。Sourceのtar.gzではないのに注意。
* リリース用パッケージを作成
  * Windowsの手順は不要。現在はGithub Actionsの方で自動で実施している。
* リポジトリーの更新
    * `rake yum`の際には、https://github.com/rpm-software-management/createrepo_c が必要で、独自でビルドする必要がある旨記載する。
    * rpmが古かったりすると動かないので、可能な限り最新のOSを使うことを推奨
* リリースアナウンス
  * メーリスにアナウンスしなくなったので、代わりにdiscussionsに書く旨記載する
  * そもそもアナウンスのあり方を見直したいという話もあるが

**Comment by komainu8** [comment]
We already updated at #89.
