### ISSUE TITLE
doc ja: @~ operator

### ISSUE THREAD

**Issue by hiroyuki-sato** [pgroonga/pgroonga.github.io#9]
# 概要

``@~``はPGroonga独自の演算子です。``@~``演算子は、右辺の``text``型の値が、左辺の``text``型のサブセットの値なら真を返します。

## 構文

この演算子の構文は次の通りです。

```
text_column @~ text_query
```

``text_column``は``text``型または``varchar``型のカラムです。
``text_query``はクエリーとして使う``text``型または``varchar``型のカラムです。

## 使い方

例に使うサンプルスキーマとデータは次の通りです。

```sql
CREATE TABLE memos (
  id integer,
  content text
);

INSERT INTO memos VALUES (1, 'PostgreSQL is a RDBMS.');
INSERT INTO memos VALUES (2, 'Groonga is fast full text search engine.');
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga.');

CREATE INDEX grnindex ON memos USING pgroonga (content pgroonga.text_regexp_ops);

```

pgroonga.XXX_regexp_ops``のXXXの部分はカラムの型によって異なる値を指定します。

* varcharの場合: ``pgroonga.varchar_regexp_ops``を指定します。
* textの場合: ``pgroonga.text_regexp_ops``を指定します。

カラムがvarcharの場合は、最大文字数は最大バイト数が4096バイト以下になるように指定する必要があります。PGroongaのインデックスの最大長は、4096バイトだからです。たとえば、UTF-8エンコーディングを使う場合は最大文字数は1023文字以下にする必要があります。なぜなら、UTF-8エンコーディングのvarcharは1文字あたり4バイト確保し、PostgreSQLはメタデータ用に4バイトを確保するからです。

なお、一般ユーザ権限で、``CREATE INDEX``を実行する場合は、対象のユーザへ``pgroonga``スキーマのアクセス権限を付与しておきます。詳細は``create extensions pgroonga``を参照してください。

シーケンシャルスキャンを無効にします。

```
SET enable_seqscan = off;
```

マッチする例は次の通りです。

```sql
SELECT id, content
  FROM memos
  WHERE content @~ 'groonga'; 

 id |                        content                        
----+-------------------------------------------------------
  2 | Groonga is fast full text search engine.
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(2 rows)

```

右辺に指定する文字列は正規表現を利用します。また、アルファベットの場合はすべての文字を小文字にします。PGroongaはなるべくインデックスにヒットするようにすべての大文字を小文字に変換してから、インデックスに登録するからです。

つまり、検索文字に、``pgroonga``を指定した場合は、``pgroonga``、``PGroonga``のどちらもヒットします。

正規表現の演算子を使った例は次のとおりです。

```sql
SELECT id, content
  FROM memos
 WHERE content @~ 'Groonga\.\z'; 
 
 id |                        content                        
----+-------------------------------------------------------
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(1 row)
```

マッチしない例は次のとおりです。

```sql
SELECT id, content
  FROM memos
  WHERE content @~ 'PGroonga'; 
 id |                        content                        
----+-------------------------------------------------------
  2 | Groonga is fast full text search engine.
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(2 rows)

```

**と思ったが、上記のクエリは結果が出力される。**

* 右辺も大文字を小文字に変換しているのか？

**Comment by hiroyuki-sato** [comment]
* 英文を書く前に、日本語で整理
* 日本語の内容がOKなら英文に変換

疑問点
* ``content @~ 'PGroonga';``はマッチしないと思ったがマッチする。なぜか？
* ``pgroonga.varchar_regexp_ops``と``pgroonga.text_regexp_ops``の違いは、インデックスをかけるカラムが、varcharか、textかの違いのみという理解でよいか？

**Comment by kou** [comment]
> * `content @~ 'PGroonga';`はマッチしないと思ったがマッチする。なぜか？

インデックスを使ったときは正規化するのでマッチするんです。インデックスを使っていないときは正規化をしないのでマッチしません。

このようにインデックスを使うかどうかで挙動が変わるため大文字を使って正規表現のパターンを指定することを非推奨にしています。

> `pgroonga.varchar_regexp_ops`と`pgroonga.text_regexp_ops`の違いは、インデックスをかけるカラムが、`varchar`か、`text`かの違いのみという理解でよいか？

はい、そうです。

なお、`varchar`にはインデックスを使った`LIKE`/`ILIKE`を使えないので、`pgroonga.varchar_regexp_ops`を使っているときは`LIKE`/`ILIKE`は必ずシーケンシャルサーチになります。

**Comment by hiroyuki-sato** [comment]
まとめました。網羅はしたつもりですが、もう少しわかりやす方が良さそうですね。

# 概要

``@~``はPGroonga独自の演算子です。``@~``演算子は、右辺の``text``型の値が、左辺の``text``型のサブセットの値なら真を返します。

## 構文

この演算子の構文は次の通りです。

```
text_column @~ text_query
```

``text_column``は``text``型または``varchar``型のカラムです。
``text_query``はクエリーとして使う``text``型または``varchar``型のカラムです。

## 使い方

例に使うサンプルスキーマとデータは次の通りです。

```sql
CREATE TABLE memos (
  id integer,
  content text
);

INSERT INTO memos VALUES (1, 'PostgreSQL is a RDBMS.');
INSERT INTO memos VALUES (2, 'Groonga is fast full text search engine.');
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga.');

CREATE INDEX grnindex ON memos USING pgroonga (content pgroonga.text_regexp_ops);

```

pgroonga.XXX_regexp_ops``のXXXの部分はインデックスを作成するカラムの型によって異なる値を指定します。

* varcharの場合: ``pgroonga.varchar_regexp_ops``を指定します。
* textの場合: ``pgroonga.text_regexp_ops``を指定します。

シーケンシャルスキャンを無効にします。

```
SET enable_seqscan = off;
```

マッチする例は次の通りです。

```sql
SELECT id, content
  FROM memos
  WHERE content @~ 'groonga'; 

 id |                        content                        
----+-------------------------------------------------------
  2 | Groonga is fast full text search engine.
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(2 rows)

```

右辺に指定する文字列は正規表現を利用します。利用可能なインデックスは[7.13.3. インデックス](http://groonga.org/ja/docs/reference/regular_expression.html#index)を参照してください。

右辺に指定する文字列がアルファベットの場合はすべての文字を小文字にします。PGroongaはなるべくインデックスにヒットするようにすべての大文字を小文字に変換してから、インデックスに登録するからです。

つまり、検索文字に、``pgroonga``を指定した場合は、``pgroonga``、``PGroonga``のどちらもヒットします。

正規表現の演算子を使った例は次のとおりです。

```sql
SELECT id, content
  FROM memos
 WHERE content @~ 'Groonga\.\z'; 
 
 id |                        content                        
----+-------------------------------------------------------
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(1 row)
```

非推奨の使用例は次のとおりです。

```sql
SELECT id, content
  FROM memos
  WHERE content @~ 'PGroonga'; 
 id |                        content                        
----+-------------------------------------------------------
  2 | Groonga is fast full text search engine.
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(2 rows)

```

``PGroonga``のように大文字を指定することは非推奨です。PGroongaのインデックスを使ったときは正規化するのでマッチしますが、インデックスを使っていないときは正規化をしないのでマッチしません。

つまり、インデックスを使うかどうかで挙動が変わるため大文字を使って正規表現のパターンを指定することを非推奨にしています。

## 注意点

### varcharカラムについて

* 最大文字数は4096バイト以下(UTF-8の場合1023文字以下)にしてください。
* LIKE/ILIKEを使った場合、必ずシーケンシャルサーチになります。

カラムがvarcharの場合は、最大文字数は最大バイト数が4096バイト以下になるように指定する必要があります。PGroongaのインデックスの最大長は、4096バイトだからです。たとえば、UTF-8エンコーディングを使う場合は最大文字数は1023文字以下にする必要があります。なぜなら、UTF-8エンコーディングのvarcharは1文字あたり4バイト確保し、PostgreSQLはメタデータ用に4バイトを確保するからです。

また、``varchar``カラムにはPGroongaのインデックスを使ったLIKE/ILIKEを使えません。そのため``pgroonga.varchar_regexp_ops``を使っているときはLIKE/ILIKEは必ずシーケンシャルサーチになります。

### 一般ユーザで``CREATE INDEX``を利用する場合

一般ユーザ権限で、``CREATE INDEX``を実行する場合は、対象のユーザへ``pgroonga``スキーマのアクセス権限を付与しておきます。詳細は``create extensions pgroonga``を参照してください。

**Comment by kou** [comment]
だいたいよさそうなんですが、細かいところがちょっとアレなんですよねぇ。どうしたらよいかしら。

たとえば。。。

> `@~`はPGroonga独自の演算子です。`@~`演算子は、右辺の`text`型の値が、左辺の`text`型のサブセットの値なら真を返します。

後半は「`@~`演算子は正規表現マッチ演算子です。」でいいです！

他にもちょこちょこあるんですが、どう進めるのがよいかしら。。。

**Comment by hiroyuki-sato** [comment]
どうするのが良いんでしょうね。

日本語で一回書かないと英語にできないんですが、
私の英語力の問題で、日本語で書けたからといって英語にできないという悲しい問題があります。
もうここまで書いたからズバッと須藤さんに直していただいても問題ないですよ。

構成とかが問題なければ英文を先に作ってしまうのが良いようにも思います。

**Comment by hiroyuki-sato** [comment]
もし共同してやるなら、doc専用のブランチを作って、修正して
OKだったら、マージするというのが良いように思います。

**Comment by hiroyuki-sato** [comment]
色々コメントを書いた割にここに書いてしましますが、、
文章を見直ました。

``text_query``はクエリーとして使う``text``型または``varchar``型のカラムです。

これはどう直したら良いかな？と思案中です。


# 概要

``@~``はPGroonga独自の演算子です。``@~``演算子は正規表現マッチ演算子です。

## 構文

この演算子の構文は次の通りです。

```
text_column @~ text_query
```

``text_column``は``text``型または``varchar``型のカラムです。
``text_query``はクエリーとして使う``text``型または``varchar``型のカラムです。

## 使い方

例に使うサンプルスキーマとデータは次の通りです。

```sql
CREATE TABLE memos (
  id integer,
  content text
);

INSERT INTO memos VALUES (1, 'PostgreSQL is a RDBMS.');
INSERT INTO memos VALUES (2, 'Groonga is fast full text search engine.');
INSERT INTO memos VALUES (3, 'PGroonga is a PostgreSQL extension that uses Groonga.');

CREATE INDEX grnindex ON memos USING pgroonga (content pgroonga.text_regexp_ops);
```

pgroonga.XXX_regexp_ops``のXXXの部分はカラムの型によって異なる値を指定します。

* varcharの場合: ``pgroonga.varchar_regexp_ops``を指定します。
* textの場合: ``pgroonga.text_regexp_ops``を指定します。

シーケンシャルスキャンを無効にします。

```
SET enable_seqscan = off;
```

マッチする例は次のとおりです。検索文字に``pgroonga``を指定した場合は、``pgroonga``、``PGroonga``のどちらもヒットします。

```sql
SELECT id, content
  FROM memos
  WHERE content @~ 'groonga'; 

 id |                        content                        
----+-------------------------------------------------------
  2 | Groonga is fast full text search engine.
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(2 rows)

```

右辺は正規表現を利用します。利用可能な正規表現はGroongaのドキュメント[7.13.3. インデックス](http://groonga.org/ja/docs/reference/regular_expression.html#index)を参照してください。


正規表現のメタ文字列を使った例は次の通りです。

```sql
SELECT id, content
  FROM memos
 WHERE content @~ 'Groonga\.\z'; 
 
 id |                        content                        
----+-------------------------------------------------------
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(1 row)
```

非推奨の使用例は次のとおりです。


```sql
SELECT id, content
  FROM memos
  WHERE content @~ 'PGroonga'; 
 id |                        content                        
----+-------------------------------------------------------
  2 | Groonga is fast full text search engine.
  3 | PGroonga is a PostgreSQL extension that uses Groonga.
(2 rows)

```

右辺の文字列がアルファベットの場合はすべての文字を小文字にしてください。PGroongaは
インデックスを使うかどうかで挙動が変わり、検索にヒットしたりしなかったりするためです。

## 注意点

### varcharカラムについて

* 最大文字数は4096バイト以下(UTF-8の場合1023文字以下)にしてください。
* LIKE/ILIKEを使った場合、必ずシーケンシャルサーチになります。

カラムがvarcharの場合は、最大文字数は最大バイト数が4096バイト以下になるように指定する必要があります。PGroongaのインデックスの最大長は、4096バイトだからです。たとえば、UTF-8エンコーディングを使う場合は最大文字数は1023文字以下にする必要があります。なぜなら、UTF-8エンコーディングのvarcharは1文字あたり4バイト確保し、PostgreSQLはメタデータ用に4バイトを確保するからです。

また、``varchar``カラムにはPGroongaのインデックスを使ったLIKE/ILIKEを使えません。そのため``pgroonga.varchar_regexp_ops``を使っているときはLIKE/ILIKEは必ずシーケンシャルサーチになります。

### 一般ユーザで``CREATE INDEX``を利用する場合

一般ユーザ権限で、``CREATE INDEX``を実行する場合は、対象のユーザへ``pgroonga``スキーマのアクセス権限を付与しておきます。詳細は``create extensions pgroonga``を参照してください。

**Comment by kou** [comment]
このままにしておくのはアレなので書き始めてみました。（途中です。）

https://github.com/pgroonga/pgroonga.github.io/commit/3aaa90e0830e94a3103cb04048869ab80aba7890

**Comment by kou** [comment]
まとめました。 http://pgroonga.github.io/ja/reference/operators/regular-expression.html

`varchar`の最大サイズと`LIKE/ILIKE`と`CREATE INDEX`の権限以外は入れたつもりです。

`varchar`の最大サイズは`pgroonga.varchar_full_text_search_ops`とか`pgroonga.varchar_ops`とか`pgroonga.varchar_array_ops`でも同じなので別の場所でまとめて説明するのがいいんじゃないかと思いました。

`LIKE/ILIKE`は`LIKE`は http://pgroonga.github.io/ja/reference/operators/like.html に`varchar`だとダメですよと書くのがいいんじゃないかと思いました。`ILIKE`はまだドキュメント自体書いていませんね。。。

`CREATE INDEX`の権限は http://pgroonga.github.io/ja/reference/create-index-using-pgroonga.html の方がいいんじゃないかと思いました。

確認おねがいします。

**Comment by hiroyuki-sato** [comment]
ありがとうございます。

## ``@~``について

> たとえば、パターンに「Groonga」を使ってはいけません。そうではなく、「groonga」を使うべきです。なぜなら、「G」は「g」に正規化されるからです。

ここの「なぜなら」以降がちょっと初心者にはわかりづらいんじゃないかと思いました。

検索対象のカラムに「Groonga」があった場合、正規化して「groonga」になりますが、パターンパターンは正規化をしないので、マッチしないためです。
(ちょっといい表現ではないですが..)

あと、次の点を簡単に書いておくと親切かと思います。
* 全部の正規表現がサポートされているわけではないこと
* ()などが使われた場合、インデックスが使われないこと

## ``LIKE/ILIKE``

これはlikeの説明の場所で良いと思います。

## ``CREATE INDEX``権限の説明

いいと思います。
(この場所で良いかなとも思ったのですが、迷いました)

**Comment by kou** [comment]
> 対象文字列 = 検索対象のカラムであっていますでしょうか？

あっていないです。「兼宅対象のカラム」は入れ物で「対象文字列」はカラムの中に入っているもの（中身）です。

> ここの「なぜなら」以降がちょっと初心者にはわかりづらいんじゃないかと思いました。

↓にしました。

> なぜなら、対象テキスト中の「G」は「g」に正規化されるからです。対象テキスト中に「Groonga」という文字列は決して現れません。

> あと、次の点を簡単に書いておくと親切かと思います。

次のようにしておきました。

> いくつかのシンプルが正規表現のパターンはGroonga内でインデックスを使って検索します。インデックスを使った場合は非常に高速です。インデックスを使って検索可能なパターンの詳細はGroongaの正規表現のドキュメントを参照してください。
>
> もし、正規表現のパターンをインデックスを使って検索できない場合、Groonga内でシーケンシャルスキャンで検索します。
>
> EXPLAINでPostgreSQLがPGroongaのインデックスを使っているとレポートするときでも、Groongaは正規表現のパターンを使った検索をシーケンシャルスキャンで実現するかもしれないことに注意してください。

**Comment by hiroyuki-sato** [comment]
ありがとうございます。良いと思います。

**Comment by kou** [comment]
確認ありがとうございます。
